#!/bin/sh
#protected_branch='master'
#current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

echo -e "Running pre push checks..."

#####Project compiler#####
echo -e "Trying to build tests project..."
#Let's speed things up a little bit
DOTNET_CLI_TELEMETRY_OPTOUT=1
DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1    
# build the project
dotnet build
# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
  echo -e "Failed to build the project, please fix this and push again"
  echo ""
  exit $rc
fi

#####Project unit test#####
# TODO: change this to your test project directory

cd WebApiNinjectStudio.UnitTests
echo -e "Running unit tests..."
echo ""

# run the unit tests
dotnet test

# $? is a shell variable which stores the return code from what we just ran
rc=$?
if [[ $rc != 0 ]] ; then
    # A non-zero return code means an error occurred, so tell the user and exit
    echo -e "Unit tests failed, please fix and push again"
    echo ""
    exit $rc
fi

# Everything went OK so we can exit with a zero
echo -e "Pre push check passed!"
echo ""

exit 0
